export const SET_BUTTON_ACTIVE = 'SET_BUTTON_ACTIVE'
export const SET_BUTTON_INACTIVE = 'SET_BUTTON_INACTIVE'

export const COLLECT_FILTER = 'COLLECT_FILTER'
export const REMOVE_FILTER = 'REMOVE_FILTER'
export const APPLY_FILTER = 'APPLY_FILTER'